"""model shimming changed

Revision ID: 5db7a75d63ca
Revises: ed32c570dc6d
Create Date: 2023-11-30 16:35:40.605357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db7a75d63ca'
down_revision = 'ed32c570dc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shimming', schema=None) as batch_op:
        batch_op.alter_column('pinion_value',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=50),
               existing_nullable=False)
        batch_op.alter_column('backlash_value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Float(precision=255),
               nullable=False)
        batch_op.alter_column('shim_left',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('shim_right',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shimming', schema=None) as batch_op:
        batch_op.alter_column('shim_right',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shim_left',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('backlash_value',
               existing_type=sa.Float(precision=255),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('pinion_value',
               existing_type=sa.Float(precision=50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
